#!/bin/bash

# Chemins des fichiers et dossiers
script_dir="/root/Script_Prod"
script_file="$script_dir/git_auto"
github_url="https://raw.githubusercontent.com/Ezio-33/Script_Prod/master/Script_git/git_auto"

# Création du dossier s'il n'existe pas déjà
mkdir -p "$script_dir"

# Téléchargement du script git_auto depuis GitHub
curl_options="-fsSL" 
if curl $curl_options -o "$script_file" -z "$script_file" "$github_url"; then
	echo ""
	echo -e "\e[1;32mScript git_auto téléchargé avec succès.\e[0m"
	echo ""
else
	echo ""
	echo -e "\e[1;31mErreur lors du téléchargement du script git_auto depuis GitHub.\e[0m"
	echo ""
	exit 1
fi

# Attribution des droits d'exécution au script
chmod u+x "$script_file"

# Vérification si le script est déjà dans le PATH
if ! command -v git_auto >/dev/null; then
	# Ajout du dossier au PATH de manière permanente
	if ! grep -q "export PATH=\$PATH:$script_dir" ~/.bashrc; then
		echo "export PATH=\$PATH:$script_dir" >> ~/.bashrc
	fi
	# Vérifie si le fichier .bashrc existe
if [ -f ~/.bashrc ]; then
    # Utilise sed pour décommenter les lignes
    sed -i 's/#if \[ -f \/etc\/bash_completion \] && ! shopt -oq posix; then/if [ -f \/etc\/bash_completion ] && ! shopt -oq posix; then/' ~/.bashrc
    sed -i 's/#    . \/etc\/bash_completion/    . \/etc\/bash_completion/' ~/.bashrc
    sed -i 's/#fi/fi/' ~/.bashrc
	# Rechargement du fichier .bashrc pour appliquer les modifications
	source ~/.bashrc
fi

# Auto-suppression du script
rm -- "$0"

# Affichage du message en vert et en gras
echo -e "\e[1;32mInstallation et configuration terminées.\e[0m"