#!/bin/bash

# Chemins des fichiers et dossiers
script_dir="/root/.Script_Prod"
github_url=("https://raw.githubusercontent.com/Ezio-33/Script_Prod/master/Script_git/git_auto" "https://raw.githubusercontent.com/Ezio-33/Script_Prod/master/Script_git/Preparation_Projet")

# Création du dossier s'il n'existe pas déjà
mkdir -p "$script_dir"

# Téléchargement des scripts depuis GitHub
curl_options="-fsSL" 
for url in "${github_url[@]}"; do
    script_file="$script_dir/$(basename $url)"
    if curl $curl_options -o "$script_file" -z "$script_file" "$url"; then
        echo ""
        echo -e "\e[1;32mScript $(basename $url) téléchargé avec succès.\e[0m"
        echo ""
    else
        echo ""
        echo -e "\e[1;31mErreur lors du téléchargement du script $(basename $url) depuis GitHub.\e[0m"
        echo ""
        exit 1
    fi
    # Attribution des droits d'exécution au script
    chmod u+x "$script_file"
done

# Vérification si le script est déjà dans le PATH
if ! command -v git_auto >/dev/null; then
    # Ajout du dossier au PATH de manière permanente
    if ! grep -q "export PATH=\$PATH:$script_dir" ~/.bashrc; then
        echo "export PATH=\$PATH:$script_dir" >> ~/.bashrc
    fi
    # Vérifie si le fichier .bashrc existe
    if [ -f ~/.bashrc ]; then
        # Utilise sed pour décommenter les lignes
        sed -i '/^#if \[ -f \/etc\/bash_completion \] && ! shopt -oq posix; then/s/^#//' ~/.bashrc
        sed -i '/^#    \. \/etc\/bash_completion/s/^#//' ~/.bashrc
        sed -i '/^#fi/s/^#//' ~/.bashrc
    fi
# Rechargement du fichier .bashrc pour appliquer les modifications
source ~/.bashrc
fi

# Auto-suppression du script
rm -- "${BASH_SOURCE[0]}"

# Vérification de la suppression du fichier
if [ ! -f "${BASH_SOURCE[0]}" ]; then
    echo -e "\e[1;32mLe fichier d'installation a été supprimé avec succès.\e[0m"
    echo ""
else
    echo -e "\e[1;31mErreur lors de la suppression du fichier d'installation.\e[0m"
    echo ""
    exit 1
fi

# Affichage du message en vert et en gras
echo -e "\e[1;32mInstallation et configuration terminées.\e[0m"
echo ""