#!/bin/bash

# Vérifie et ajoute un saut de ligne à la fin des fichiers .py si nécessaire
for file in *.py; do
    if [ -f "$file" ]; then
        # Vérifie si le fichier ne se termine pas par un saut de ligne
        if [ -s "$file" ] && [ $(tail -c 1 "$file" | wc -l) -eq 0 ]; then
            echo "Ajout d'un saut de ligne à la fin du fichier $file"
            echo "" >> "$file"
        fi
    fi
done

# Correction automatique avec autopep8 (exclusion des fichiers main)
for file in *.py; do
    if [[ "$file" != *"main"* ]]; then
        autopep8 --in-place --aggressive --aggressive "$file"
    fi
done

# Vérification avec flake8 (exclusion des fichiers main)
for file in *.py; do
    if [[ "$file" != *"main"* ]]; then
        flake8 "$file"
    fi
done

# Nettoyer l'écran
clear

# Vérification finale avec pycodestyle (exclusion des fichiers main)
for file in *.py; do
    if [[ "$file" != *"main"* ]]; then
        pycodestyle "$file"
    fi
done
